#!/bin/bash

function display_help {
  flags_help
  echo

  # taken from shocco
  grep '^#/' <"$shome/$(basename $(dirname -- "$0"))/$(basename -- "$0")" | cut -c4-
}

function check_help {
  # taken from shocco
  if expr -- "$*" : ".*--help" >/dev/null; then
    display_help
    exit 0
  fi
}

function require {
  if [[ "$#" > 0 ]]; then
    local nm_lib="_${1#_}"; shift
    source "$nm_lib" "$@"
  fi
}

function parse_command_line {
  if [[ "$FLAGS_SUB" = "$FLAGS_TRUE" && "$@" > 0 ]]; then
    export POSIXLY_CORRECT=1
  fi

  if ! FLAGS "$@"; then
    unset POSIXLY_CORRECT
    if [[ "$flags_error" = "help requested" ]]; then
      echo ""
      display_help
      exit 0
    fi
    
    return 4
  fi

  unset POSIXLY_CORRECT
  return 0
}

function ryaml {
  ruby -ryaml -e 'def ps x; unless x.nil?; puts (x.class == String || x.class == Fixnum) ? x : x.to_yaml; end; end; ps ARGV[1..-1].inject(YAML.load(File.read(ARGV[0]))) {|acc, key| acc[acc.class == Array ? key.to_i : (m = key.match(/^:(.*)$/); m ? m[1].to_sym : key)] }' "$@" 2>&1
}

function random_str {
  echo "$(date +%s).$$.$RANDOM"
}

function runmany {
  local cpu="$1"; shift
  local args="$1"; shift
  local cmd="$1"; shift
  if [[ "$#" = 0 ]]; then
    cat
  else
    echo "$@"
  fi | xargs -P $cpu -n $args -- bash -c "$cmd" ""
}

function mark_log {
  local nm_mark="$1"; shift
  touch "$tmp_switch/wait-$nm_mark"
  echo $tmp_switch $nm_mark
  while [[ -f "$tmp_switch/wait-$nm_mark" ]]; do
    sleep 1
  done
}

function marked_logger {
  local nm_switch=""
  while read -r a b; do
    if [[ "$a" = "$tmp_switch" ]]; then
      nm_switch="$b"
      rm "$tmp_switch/wait-$nm_switch"
    else
      if [[ -z "$nm_switch" ]]; then
        echo "$a $b"
      else
        echo "$nm_switch: $a $b"
      fi
    fi
  done
}

function mark_stdout {
  if [[ -z "${tmp_switch:-}" ]]; then
    tmp_switch="$(mktemp -d -t XXXXXXXXX)"
  fi
  exec 1> >(marked_logger)
}

function mark_stderr {
  if [[ -z "${tmp_switch:-}" ]]; then
    tmp_switch="$(mktemp -d -t XXXXXXXXX)"
  fi
  exec 2> >(marked_logger)
}

function mark_output {
  if [[ -z "${tmp_switch:-}" ]]; then
    tmp_switch="$(mktemp -d -t XXXXXXXXX)"
  fi
  exec 1> >(marked_logger) 2>&1
}

function _main {
  : ${__jason__:=x}
  if [[ "$__jason__" != 'x' ]]; then
    return 0
  fi

  __jason__='y'

  require _shflags
}

function logger_base {
  local level="$1"; shift

  printf '[%s] %s\r\n' "$level" "$*"
}

function logger_trace {
  logger_base "TRACE" "$@"
}

function logger_debug {
  logger_base "DEBUG" "$@"
}

function logger_info {
  logger_base "INFO" "$@"
}

function logger_warn {
  logger_base "WARN" "$@"
}

function logger_error {
  logger_base "ERROR" "$@"
}

function logger_fatal {
  logger_base "FATAL" "$@"
}

_main "$@"
set -fue
